version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  bot:
    build: .
    volumes:
      - .:/bot
    command: ["./wait-for-it.sh", "redis:6379", "--", "python", "main.py"]
    ports:
      - "8082:8082"
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081
