version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dndtext
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  bot:
    build: .
    volumes:
      - .:/bot
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "main.py"]
    ports:
      - "8080:8080"
    depends_on:
      - db
